In [1]:
## Model

'''
So what I have understood is that I need to take the hidden representations of the LSTM and then use them to get the weights

Input > LSTM > Hidden Representation > Softmax Layer > Weights > Calculate Sharpe (Loss) > Train the Model

# So for simplicity, I will choose 5 stocks to invest in instead of using a 50 stocks and choosing them
the stocks will be namely > TATASTEEL.NS, SUNPHARMA.NS, RELIANCE.NS, INFY.NS, TATACONSUM.NS

'''

'\nSo what I have understood is that I need to take the hidden representations of the LSTM and then use them to get the weights\n\nInput > LSTM > Hidden Representation > Softmax Layer > Weights > Calculate Sharpe (Loss) > Train the Model\n\n# So for simplicity, I will choose 5 stocks to invest in instead of using a 50 stocks and choosing them\nthe stocks will be namely > TATASTEEL.NS, SUNPHARMA.NS, RELIANCE.NS, INFY.NS, TATACONSUM.NS\n\n'

In [2]:
import pandas as pd
import numpy as np
import yaml
import os

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import Dataset, DataLoader

from dotenv import load_dotenv
load_dotenv()

True

In [3]:
path = os.environ['PROJECT_FOLDER']

In [4]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [40]:
dataset = pd.read_csv(os.path.join(path,'data','final','Dataset.csv'))
stocks = pd.read_csv(os.path.join(path,'data','final','Stocks.csv'))

dataset.set_index('Date',inplace=True)
stocks.set_index('Date',inplace=True)

stocks = stocks[['TATASTEEL.NS_7DReturn','SUNPHARMA.NS_7DReturn','RELIANCE.NS_7DReturn','INFY.NS_7DReturn','TATACONSUM.NS_7DReturn']]

In [41]:
stocks.dropna(axis=0)

,TATASTEEL.NS_7DReturn,SUNPHARMA.NS_7DReturn,RELIANCE.NS_7DReturn,INFY.NS_7DReturn,TATACONSUM.NS_7DReturn
Date,,,,,
2021-07-26,8.713802,14.216191,3.856454,3.182425,-0.181885
2021-07-27,4.677649,14.161084,2.537607,2.777775,3.503773
2021-07-28,-3.181139,12.204837,1.164005,2.863346,1.817094
2021-07-29,-4.232028,2.506618,2.591742,4.144661,2.069443
2021-08-02,2.000431,-2.031974,1.089691,2.078288,0.859754
...,...,...,...,...,...
2026-06-04,-3.253828,1.038043,2.927967,-2.434510,0.000000
2026-06-08,0.726100,2.574483,4.640721,-2.406306,0.442840
2026-06-09,1.883061,2.905286,4.027641,-8.198727,0.315884
2026-06-10,2.583004,3.829009,5.027712,-4.414135,0.387881
2026-06-11,-2.173255,3.335733,1.276102,-7.801861,0.281648

In [42]:
dataset

,GC=F_HL,GC=F_OC,GC=F_Volatility,GC=F_Theta,SI=F_HL,SI=F_OC,SI=F_Volatility,SI=F_Theta,CL=F_HL,CL=F_OC,...,^FCHI_Volatility,^FCHI_Theta,^VIX_HL,^VIX_OC,^VIX_Volatility,^VIX_Theta,^INDIAVIX_HL,^INDIAVIX_OC,^INDIAVIX_Volatility,^INDIAVIX_Theta
Date,,,,,,,,,,,,,,,,,,,,,
2021-07-26,-0.398094,-0.199807,-0.387302,-1.093121,-0.366648,0.016640,-0.356700,-0.011802,-0.144314,-0.150827,...,-0.010667,-1.080627,0.149315,-0.696332,0.150351,-0.939089,-0.330258,0.327226,-0.316902,1.367360
2021-07-27,-0.445094,-0.221287,-0.407848,-1.372308,0.346875,-0.785101,0.407842,-1.365747,-0.498939,-0.328294,...,0.584027,1.356693,0.335931,0.585658,0.225277,0.898915,0.302109,0.192966,0.238089,0.317603
2021-07-28,-0.624530,0.004308,-0.617556,-0.030073,-0.218983,0.187433,-0.196388,1.368811,-0.699129,0.298750,...,-0.608418,-0.758356,0.285036,-0.703338,0.253656,-0.836949,-0.365939,-0.310509,-0.349361,-1.345179
2021-07-29,0.507636,1.325668,0.659063,1.248648,0.552027,1.038574,0.623284,1.332899,-0.401705,0.730586,...,-0.375896,0.146879,-0.438805,-0.079855,-0.479371,-0.339178,-0.387745,-0.062967,-0.405118,-0.286023
2021-08-02,-0.030681,0.310475,-0.087138,0.634994,-0.246038,0.167669,-0.220672,1.442240,0.730801,-1.558726,...,-0.024471,0.939834,0.160626,0.977961,0.212797,1.498324,-0.227176,0.394356,-0.218231,1.235753
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-06-04,2.045673,1.529777,1.806236,0.698820,0.884556,0.989177,0.817746,1.016652,1.073989,-1.594217,...,0.402691,-1.178046,0.013595,-0.584246,0.011899,-0.919892,-0.036871,-0.041989,-0.080682,-0.032899
2026-06-08,1.780780,0.632745,1.412665,0.320090,1.820133,1.392874,1.595135,0.850389,1.691721,-0.996748,...,0.932300,0.393674,0.460340,-0.892484,0.446763,-0.910810,-0.314399,-0.608399,-0.231355,-1.950241
2026-06-09,3.831496,-3.906050,3.873221,-1.071484,3.933660,-4.402805,4.079935,-1.284120,1.989150,-1.813094,...,1.405513,-0.978258,2.388695,1.244167,2.026823,0.802640,-0.425410,0.020945,-0.441672,0.195190
2026-06-10,3.934048,-4.926613,4.352042,-1.244263,0.595989,1.116208,0.682423,1.357270,1.348538,0.381567,...,0.780665,0.869407,0.567786,1.552404,0.726939,1.668096,-0.449198,-0.008424,-0.463966,-0.005983
2026-06-11,7.014377,2.550353,5.913315,0.412796,-0.253924,-0.082171,-0.246965,-1.142490,3.304687,-2.676761,...,0.611574,0.710272,0.924050,-1.200721,0.894210,-0.897629,-0.373869,-0.373443,-0.340256,-1.606667

In [6]:
dataset = MyDataset(X=dataset,y=stocks)

Epoch 1: -0.1636
Epoch 2: -0.2029
Epoch 3: -0.2325
Epoch 4: -0.2552
Epoch 5: -0.2782
Epoch 6: -0.3069
Epoch 7: -0.3331
Epoch 8: -0.3521
Epoch 9: -0.3659
Epoch 10: -0.3747
Epoch 11: -0.3860
Epoch 12: -0.3920
Epoch 13: -0.3972
Epoch 14: -0.3976
Epoch 15: -0.4032
Epoch 16: -0.4093
Epoch 17: -0.4122
Epoch 18: -0.4153
Epoch 19: -0.4176
Epoch 20: -0.4200
Epoch 21: -0.4247
Epoch 22: -0.4274
Epoch 23: -0.4246
Epoch 24: -0.4252
Epoch 25: -0.4303
Epoch 26: -0.4330
Epoch 27: -0.4314
Epoch 28: -0.4353
Epoch 29: -0.4361
Epoch 30: -0.4361
Epoch 31: -0.4374
Epoch 32: -0.4388
Epoch 33: -0.4386
Epoch 34: -0.4398
Epoch 35: -0.4386

In [28]:
X

tensor([[[ 3.8315e+00, -3.9060e+00,  3.8732e+00, -1.0715e+00,  3.9337e+00,
          -4.4028e+00,  4.0799e+00, -1.2841e+00,  1.9892e+00, -1.8131e+00,
           1.8579e+00, -1.1425e+00,  1.5243e+00,  2.1951e-01,  1.0950e+00,
           1.1550e-01, -2.4328e-01, -4.4120e-03, -2.6538e-01, -1.8135e-02,
          -1.2523e+00, -1.0500e-02, -1.1805e+00, -8.3288e-03, -4.4317e-01,
          -2.6055e-03, -4.7139e-01, -1.1309e-02, -4.2580e-01, -3.9368e-02,
          -4.5669e-01, -7.4323e-02, -7.1904e-01, -3.3217e-02, -6.6864e-01,
          -2.0241e-01, -5.8278e-01, -1.8268e-02, -5.9954e-01, -2.0907e-02,
           1.2954e+01, -3.9816e+00,  1.1016e+01, -6.2124e-01,  1.0112e-02,
           1.6653e-01, -1.3166e-01,  2.8125e-01,  5.3892e+00, -4.0361e+00,
           5.0072e+00, -1.2998e+00,  3.7763e+00, -3.5592e+00,  3.8220e+00,
          -1.3662e+00,  1.0792e+00, -1.2481e-01,  7.2540e-01, -1.2112e-01,
           1.4581e+00,  4.9409e-01,  1.0340e+00,  3.0124e-01,  1.6055e+00,
          -1.3379e+00,  1.4055e+00, -9.7826e-01,  2.3887e+00,  1.2442e+00,
           2.0268e+00,  8.0264e-01, -4.2541e-01,  2.0945e-02, -4.4167e-01,
           1.9519e-01],
         [ 3.9340e+00, -4.9266e+00,  4.3520e+00, -1.2443e+00,  5.9599e-01,
           1.1162e+00,  6.8242e-01,  1.3573e+00,  1.3485e+00,  3.8157e-01,
           9.8494e-01,  2.6077e-01, -8.5348e-01, -1.5997e-01, -8.2236e-01,
          -1.3560e+00, -2.2727e-01, -5.6153e-02, -2.4925e-01, -2.2659e-01,
          -1.3351e+00, -2.5810e-02, -1.2513e+00, -3.6396e-01, -3.4847e-01,
          -6.8155e-02, -3.8027e-01, -2.3897e-01, -5.1016e-01, -1.1831e-01,
          -5.3502e-01, -3.1721e-01, -8.1362e-01, -7.6309e-02, -7.4740e-01,
          -4.5997e-01, -4.9433e-01, -1.8268e-02, -5.1964e-01, -2.0907e-02,
           6.6731e+00, -6.3889e+00,  6.6323e+00, -1.5785e+00, -9.0233e-02,
           1.4522e-01, -2.1558e-01,  2.7786e-01,  8.5104e+00,  4.6591e+00,
           7.4655e+00,  1.0265e+00,  1.4633e+00,  5.5737e-02,  1.0889e+00,
          -1.3776e-02,  1.2269e+00,  6.1870e-01,  8.9387e-01,  4.9746e-01,
           1.0947e+00,  8.8685e-01,  8.5308e-01,  6.7438e-01,  9.3181e-01,
           1.0255e+00,  7.8067e-01,  8.6941e-01,  5.6779e-01,  1.5524e+00,
           7.2694e-01,  1.6681e+00, -4.4920e-01, -8.4244e-03, -4.6397e-01,
          -5.9832e-03],
         [ 7.0144e+00,  2.5504e+00,  5.9133e+00,  4.1280e-01, -2.5392e-01,
          -8.2171e-02, -2.4697e-01, -1.1425e+00,  3.3047e+00, -2.6768e+00,
           3.1299e+00, -1.1835e+00, -9.9725e-01, -2.1975e-02, -9.8292e-01,
          -4.5914e-02, -2.7353e-01,  4.7664e-02, -2.9489e-01,  2.5426e-01,
          -1.1578e+00,  2.5699e-02, -1.0976e+00,  3.2056e-01, -5.2982e-01,
           2.1391e-02, -5.5390e-01,  1.2581e-01, -5.1887e-01,  5.4417e-02,
          -5.4425e-01,  1.9989e-01, -7.2850e-01,  5.1667e-02, -6.7610e-01,
           2.0364e-01, -3.9452e-02, -1.8268e-02, -1.0869e-01, -2.0907e-02,
           8.0272e+00,  8.1267e+00,  8.1608e+00,  1.5332e+00,  2.5174e-01,
           3.1572e-01,  8.7715e-02,  4.2012e-01,  8.5468e+00,  4.4273e+00,
           7.4302e+00,  9.7699e-01,  2.3299e+00,  9.8619e-01,  1.9074e+00,
           5.1560e-01,  1.9936e+00,  2.1131e+00,  1.9836e+00,  1.2114e+00,
           2.1094e+00,  3.1051e+00,  2.6271e+00,  1.4347e+00,  8.1614e-01,
           7.9028e-01,  6.1157e-01,  7.1027e-01,  9.2405e-01, -1.2007e+00,
           8.9421e-01, -8.9763e-01, -3.7387e-01, -3.7344e-01, -3.4026e-01,
          -1.6067e+00],
         [ 3.3445e+00,  3.0552e+00,  3.2269e+00,  9.0776e-01, -3.6665e-01,
           1.6640e-02, -3.5670e-01, -1.1802e-02,  3.4186e-01, -3.7562e-01,
           1.7723e-01, -5.5663e-01, -6.1017e-01, -4.2445e-01, -5.3372e-01,
          -1.4262e+00, -2.2949e-01,  2.4625e-02, -2.5166e-01,  1.0024e-01,
          -1.1551e+00,  1.2530e-03, -1.0964e+00,  1.0305e-01, -4.6937e-01,
          -2.9286e-02, -4.9627e-01, -1.3336e-01, -3.4076e-01,  7.4712e-03,
          -3.7594e-01,  4.2433e-02, -7.5234e-01, -1.0395e-03, -6.9737e-01,
          -4.9687e-02, -7.3065e-01, -1.8268e-02, -7.3313e-01, -2.0907e-02,
           2.8682e+00,  2.8534e+00,  2.8162e+00,  1.3974e+00, -4.3044e-01,
          -1.1375e-01, -5.0659e-01, -2.6963e-01,  3.4064e+00,  6.1563e-01,
           2.6816e+00,  3.1323e-01,  1.0810e+00, -3.6520e-01,  7.8978e-01,
          -3.9977e-01, -1.9452e-01,  6.9726e-01, -1.8908e-01,  1.1138e+00,
           6.3794e-01,  1.1487e+00,  6.3484e-01,  1.0483e+00, -1.9085e-02,
           8.9954e-01,  4.4681e-02,  1.1986e+00, -4.1053e-01, -3.3906e-01,
          -3.8359e-01, -1.0635e+00, -3.4810e-01, -4.1540e-01, -3.1006e-01,
          -1.6122e+00],
         [ 9.2632e-01,  1.1538e+00,  8.7020e-01,  8.8028e-01, -3.6665e-01,
           1.6640e-02, -3.5670e-01, -1.1802e-02,  2.2523e+00, -2.9784e+00,
           2.5580e+00, -1.5616e+00, -4.5533e-01, -2.2897e-01, -5.0917e-01,
          -6.6463e-01, -2.8087e-01,  1.0132e-02, -3.0250e-01,  6.1860e-02,
          -1.2267e+00, -1.3203e-02, -1.1583e+00, -3.7033e-02, -4.9104e-01,
           1.8489e-02, -5.1694e-01,  9.4100e-02, -4.9656e-01, -2.0838e-02,
          -5.2396e-01, -2.6905e-02, -1.0394e+00,  2.1763e-02, -9.4171e-01,
           1.4519e-01, -3.5855e-01, -1.8268e-02, -3.9697e-01, -2.0907e-02,
           2.6003e+00, -2.8688e+00,  2.6247e+00, -1.6260e+00, -1.6398e-01,
           8.5732e-01, -4.9203e-03,  1.4083e+00,  4.3740e+00,  4.7024e+00,
           4.5724e+00,  1.6804e+00,  9.1181e-01,  1.3476e+00,  9.0916e-01,
           1.1780e+00,  4.8429e-02,  4.6258e-01, -8.2498e-02,  6.3977e-01,
          -4.4832e-01,  2.5069e-01, -4.9893e-01,  5.7361e-01,  1.6296e-01,
          -8.6905e-02, -4.7597e-02, -1.7437e-01, -5.2363e-01,  2.1437e-01,
          -5.4878e-01,  8.5141e-01, -3.7982e-01, -7.1359e-02, -3.9732e-01,
          -3.1818e-01],
         [ 2.8361e+00,  1.0732e+00,  2.3273e+00,  3.8163e-01,  2.1019e+00,
           5.6149e-01,  1.6424e+00,  3.1119e-01,  1.8976e+00,  1.2720e-01,
           1.4149e+00,  3.5913e-02,  2.2321e+00,  1.9651e-01,  1.6726e+00,
           6.8281e-02, -7.8241e-02, -9.3067e-02, -1.0174e-01, -2.2318e-01,
          -8.4227e-01, -5.3716e-02, -8.2505e-01, -1.7825e-01,  2.6853e-02,
          -6.4616e-02, -2.2321e-02, -1.3744e-01,  3.9027e-01, -2.4412e-01,
           3.2200e-01, -2.9406e-01, -6.8151e-01, -1.1925e-01, -6.3254e-01,
          -5.8073e-01, -2.7979e-01, -1.8268e-02, -3.2582e-01, -2.0907e-02,
           6.6145e+00, -7.9803e+00,  7.1512e+00, -1.8689e+00, -1.3959e-01,
          -1.5219e-01, -2.6651e-01, -2.9314e-01,  5.1185e+00,  4.6679e+00,
           5.0458e+00,  1.5087e+00,  1.1784e+00,  3.4927e-01,  8.6786e-01,
           2.5376e-01,  1.8756e-01,  9.7973e-01,  2.0552e-01,  1.1874e+00,
           1.4064e+00, -2.0486e+00,  1.5824e+00, -1.4168e+00,  1.4318e-01,
           7.7554e-01,  1.0211e-01,  9.6450e-01,  6.9220e-01,  1.7205e+00,
           8.8202e-01,  1.6955e+00, -3.6792e-01, -2.1821e-01, -3.6925e-01,
          -9.8459e-01],
         [ 2.8617e+00,  2.3194e+00,  2.6406e+00,  8.0040e-01, -3.6665e-01,
           1.6640e-02, -3.5670e-01, -1.1802e-02,  1.3657e+00, -2.4224e+00,
           1.7226e+00, -1.6583e+00, -9.9725e-01, -2.1975e-02, -9.8292e-01,
          -4.5914e-02, -1.4041e-01,  3.5076e-02, -1.6358e-01,  9.3007e-02,
          -1.1429e+00, -2.9161e-02, -1.0855e+00, -1.5798e-01, -3.6714e-01,
           6.1224e-03, -3.9879e-01,  1.7787e-02, -5.2290e-01, -5.6977e-02,
          -5.4867e-01, -1.3741e-01, -8.0364e-02,  3.4666e-02, -1.2444e-01,
           4.0160e-02, -5.7822e-01, -1.8268e-02, -5.9542e-01, -2.0907e-02,
           3.3519e+00, -2.1223e+00,  2.9762e+00, -1.0658e+00,  1.2385e+00,
          -1.3246e+00,  1.1097e+00, -1.0624e+00,  1.1975e+01, -1.3682e+01,
           1.3344e+01, -1.8826e+00,  1.5967e+00,  6.6617e-01,  1.2547e+00,
           4.3879e-01,  2.1861e+00, -2.3515e+00,  2.2866e+00, -1.2285e+00,
           1.3310e+00, -1.8261e-01,  8.9399e-01, -2.2032e-01,  3.2789e-01,
           1.9325e-01,  9.3987e-02,  1.9405e-01, -9.3849e-02, -7.2850e-02,
          -1.9204e-01, -9.9209e-02, -2.5493e-01,  4.6149e-01, -2.2683e-01,
           1.4900e+00]]])

In [17]:
len(dataset)

817

In [ ]:
dataset[812][0].unsqueeze(1)  

'''
Unsqueeze is done because as the model is trained as batchsize, sequencelen, features and we
have a single sequence as input, we have to unsqueeze it to add another dimension
'''

tensor([[[ 1.7381e+00,  6.3399e-02,  1.3353e+00,  3.9204e-03,  4.3819e-01,
          -4.6187e-01,  3.5383e-01, -8.3247e-01,  1.0054e+00,  7.8383e-01,
           7.8440e-01,  6.6677e-01, -5.8804e-01, -9.0976e-02, -6.4274e-01,
          -3.2847e-01, -2.4067e-01,  7.2490e-03, -2.6279e-01,  3.2253e-02,
          -1.0917e+00, -2.3474e-03, -1.0417e+00,  6.1484e-02, -4.5958e-01,
           1.2524e-02, -4.8698e-01,  5.7144e-02, -2.0942e-01,  3.1706e-02,
          -2.5102e-01,  8.3706e-02, -5.6607e-01,  1.1879e-02, -5.3857e-01,
           9.0565e-04, -3.2978e-01, -1.8268e-02, -3.7098e-01, -2.0907e-02,
           1.5941e+00,  1.0856e+00,  1.3856e+00,  8.9793e-01,  1.2192e-01,
           3.6911e-01, -2.1718e-03,  5.4806e-01,  6.2084e+00,  6.1012e+00,
           6.3469e+00,  1.6257e+00,  1.0977e+00, -1.3248e+00,  1.0380e+00,
          -1.1891e+00,  1.7587e+00, -4.0406e-02,  1.2820e+00, -2.7672e-02,
          -4.1232e-02, -7.7821e-01, -6.1762e-03, -1.2426e+00, -3.0258e-01,
          -6.0762e-01, -2.8327e-01, -1.1365e+00, -5.7452e-01, -2.9002e-01,
          -5.1502e-01, -1.3496e+00, -1.9149e-01,  3.8596e-01, -1.8961e-01,
           1.1270e+00]],

        [[ 1.2767e+00, -1.8488e+00,  1.3705e+00, -1.1571e+00, -6.6811e-02,
           1.6640e-02, -1.1758e-01, -1.1802e-02,  8.1660e-01,  1.5292e+00,
           9.1880e-01,  1.3241e+00,  7.1695e-01, -1.6664e+00,  9.3092e-01,
          -1.3555e+00, -2.0740e-01, -1.5289e-03, -2.2992e-01, -7.5547e-03,
          -1.2503e+00, -3.2448e-03, -1.1788e+00,  8.5936e-02, -4.6786e-01,
          -5.5877e-03, -4.9497e-01, -2.4113e-02,  1.1128e-01, -1.8471e-03,
           5.3257e-02,  8.4391e-03, -9.7006e-01,  2.1927e-02, -8.8265e-01,
           1.1762e-01, -4.9612e-01, -1.8268e-02, -5.2125e-01, -2.0907e-02,
           2.4826e+00, -3.9526e+00,  2.9552e+00, -2.0908e+00, -1.3624e-01,
           5.9217e-02, -2.6297e-01,  1.2743e-01,  4.3336e+00, -2.0316e+00,
           3.6463e+00, -8.3828e-01,  7.6337e-01,  1.0943e+00,  7.0725e-01,
           1.0515e+00,  8.4988e-01,  1.3691e+00,  8.4571e-01,  1.1824e+00,
           1.1701e+00,  5.0147e-01,  8.0966e-01,  3.5157e-01,  1.0808e+00,
           2.0476e+00,  1.3900e+00,  1.4666e+00, -5.1232e-01,  1.3031e-01,
          -5.5181e-01,  4.7770e-01, -4.3929e-01, -1.6366e-01, -4.3960e-01,
          -1.0373e+00]],

        [[ 2.0457e+00,  1.5298e+00,  1.8062e+00,  6.9882e-01,  8.8456e-01,
           9.8918e-01,  8.1775e-01,  1.0167e+00,  1.0740e+00, -1.5942e+00,
           1.1287e+00, -1.3448e+00, -4.1110e-01,  1.1602e-01, -4.8976e-01,
           3.4541e-01,  9.9934e-02, -4.2252e-02,  7.3938e-02, -7.6177e-02,
          -1.1051e+00, -8.6941e-03, -1.0532e+00,  1.5310e-02,  7.1053e-02,
           3.4096e-02,  1.9671e-02,  4.8323e-02,  8.3093e-01,  1.7321e-02,
           7.3668e-01,  1.9009e-02,  2.1709e-01,  2.5501e-02,  1.2895e-01,
           5.1079e-03,  1.6268e-02, -1.8268e-02, -5.8356e-02, -2.0907e-02,
           3.9901e+00,  5.1607e+00,  4.3895e+00,  1.7757e+00,  5.6023e-01,
          -5.1108e-01,  3.5091e-01, -6.1488e-01,  4.8807e+00, -2.7473e+00,
           4.2395e+00, -1.0047e+00,  1.6725e+00, -1.3984e+00,  1.4926e+00,
          -1.0240e+00,  1.0081e+00, -1.0347e+00,  8.7333e-01, -8.8435e-01,
           4.2545e-01,  1.3269e-01,  1.6852e-01,  9.6227e-02,  4.0153e-01,
          -1.0228e+00,  4.0269e-01, -1.1780e+00,  1.3595e-02, -5.8425e-01,
           1.1899e-02, -9.1989e-01, -3.6871e-02, -4.1989e-02, -8.0682e-02,
          -3.2899e-02]],

        [[ 1.7808e+00,  6.3274e-01,  1.4127e+00,  3.2009e-01,  1.8201e+00,
           1.3929e+00,  1.5951e+00,  8.5039e-01,  1.6917e+00, -9.9675e-01,
           1.3743e+00, -7.4960e-01, -2.3416e-01, -8.1542e-01, -9.7370e-02,
          -1.4262e+00, -1.9649e-01,  7.0688e-03, -2.1912e-01,  2.2012e-02,
          -1.2712e+00, -1.4392e-03, -1.1968e+00,  1.2010e-01, -2.7363e-01,
           3.2993e-03, -3.0953e-01,  2.2788e-03, -3.5262e-01,  4.9244e-02,
          -3.8667e-01,  1.4302e-01, -5.1089e-01,  5.1532e-02, -4.9086e-01,
           1.4385e-01, -5.6631e-01, -1.8268e-02, -5.8466e-01, -2.0907e-02,
           3.4439e+00, -2.6711e+00,  3.1794e+00, -1.2685e+00,  3.2694e-01,
           8.2254e-01,  3.0226e-01,  9.7519e-01,  6.2905e+00,  4.1528e+00,
           5.6836e+00,  1.1799e+00,  3.2474e+00, -1.7798e+00,  2.8204e+00,
          -8.5335e-01,  4.1590e-01, -1.0482e-01,  1.7797e-01, -1.5800e-01,
           1.6427e+00, -2.6940e+00,  2.0981e+00, -1.5991e+00,  1.3027e+00,
           5.4067e-01,  9.3230e-01,  3.9367e-01,  4.6034e-01, -8.9248e-01,
           4.4676e-01, -9.1081e-01, -3.1440e-01, -6.0840e-01, -2.3136e-01,
          -1.9502e+00]],

        [[ 3.8315e+00, -3.9060e+00,  3.8732e+00, -1.0715e+00,  3.9337e+00,
          -4.4028e+00,  4.0799e+00, -1.2841e+00,  1.9892e+00, -1.8131e+00,
           1.8579e+00, -1.1425e+00,  1.5243e+00,  2.1951e-01,  1.0950e+00,
           1.1550e-01, -2.4328e-01, -4.4120e-03, -2.6538e-01, -1.8135e-02,
          -1.2523e+00, -1.0500e-02, -1.1805e+00, -8.3288e-03, -4.4317e-01,
          -2.6055e-03, -4.7139e-01, -1.1309e-02, -4.2580e-01, -3.9368e-02,
          -4.5669e-01, -7.4323e-02, -7.1904e-01, -3.3217e-02, -6.6864e-01,
          -2.0241e-01, -5.8278e-01, -1.8268e-02, -5.9954e-01, -2.0907e-02,
           1.2954e+01, -3.9816e+00,  1.1016e+01, -6.2124e-01,  1.0112e-02,
           1.6653e-01, -1.3166e-01,  2.8125e-01,  5.3892e+00, -4.0361e+00,
           5.0072e+00, -1.2998e+00,  3.7763e+00, -3.5592e+00,  3.8220e+00,
          -1.3662e+00,  1.0792e+00, -1.2481e-01,  7.2540e-01, -1.2112e-01,
           1.4581e+00,  4.9409e-01,  1.0340e+00,  3.0124e-01,  1.6055e+00,
          -1.3379e+00,  1.4055e+00, -9.7826e-01,  2.3887e+00,  1.2442e+00,
           2.0268e+00,  8.0264e-01, -4.2541e-01,  2.0945e-02, -4.4167e-01,
           1.9519e-01]],

        [[ 3.9340e+00, -4.9266e+00,  4.3520e+00, -1.2443e+00,  5.9599e-01,
           1.1162e+00,  6.8242e-01,  1.3573e+00,  1.3485e+00,  3.8157e-01,
           9.8494e-01,  2.6077e-01, -8.5348e-01, -1.5997e-01, -8.2236e-01,
          -1.3560e+00, -2.2727e-01, -5.6153e-02, -2.4925e-01, -2.2659e-01,
          -1.3351e+00, -2.5810e-02, -1.2513e+00, -3.6396e-01, -3.4847e-01,
          -6.8155e-02, -3.8027e-01, -2.3897e-01, -5.1016e-01, -1.1831e-01,
          -5.3502e-01, -3.1721e-01, -8.1362e-01, -7.6309e-02, -7.4740e-01,
          -4.5997e-01, -4.9433e-01, -1.8268e-02, -5.1964e-01, -2.0907e-02,
           6.6731e+00, -6.3889e+00,  6.6323e+00, -1.5785e+00, -9.0233e-02,
           1.4522e-01, -2.1558e-01,  2.7786e-01,  8.5104e+00,  4.6591e+00,
           7.4655e+00,  1.0265e+00,  1.4633e+00,  5.5737e-02,  1.0889e+00,
          -1.3776e-02,  1.2269e+00,  6.1870e-01,  8.9387e-01,  4.9746e-01,
           1.0947e+00,  8.8685e-01,  8.5308e-01,  6.7438e-01,  9.3181e-01,
           1.0255e+00,  7.8067e-01,  8.6941e-01,  5.6779e-01,  1.5524e+00,
           7.2694e-01,  1.6681e+00, -4.4920e-01, -8.4244e-03, -4.6397e-01,
          -5.9832e-03]],

        [[ 7.0144e+00,  2.5504e+00,  5.9133e+00,  4.1280e-01, -2.5392e-01,
          -8.2171e-02, -2.4697e-01, -1.1425e+00,  3.3047e+00, -2.6768e+00,
           3.1299e+00, -1.1835e+00, -9.9725e-01, -2.1975e-02, -9.8292e-01,
          -4.5914e-02, -2.7353e-01,  4.7664e-02, -2.9489e-01,  2.5426e-01,
          -1.1578e+00,  2.5699e-02, -1.0976e+00,  3.2056e-01, -5.2982e-01,
           2.1391e-02, -5.5390e-01,  1.2581e-01, -5.1887e-01,  5.4417e-02,
          -5.4425e-01,  1.9989e-01, -7.2850e-01,  5.1667e-02, -6.7610e-01,
           2.0364e-01, -3.9452e-02, -1.8268e-02, -1.0869e-01, -2.0907e-02,
           8.0272e+00,  8.1267e+00,  8.1608e+00,  1.5332e+00,  2.5174e-01,
           3.1572e-01,  8.7715e-02,  4.2012e-01,  8.5468e+00,  4.4273e+00,
           7.4302e+00,  9.7699e-01,  2.3299e+00,  9.8619e-01,  1.9074e+00,
           5.1560e-01,  1.9936e+00,  2.1131e+00,  1.9836e+00,  1.2114e+00,
           2.1094e+00,  3.1051e+00,  2.6271e+00,  1.4347e+00,  8.1614e-01,
           7.9028e-01,  6.1157e-01,  7.1027e-01,  9.2405e-01, -1.2007e+00,
           8.9421e-01, -8.9763e-01, -3.7387e-01, -3.7344e-01, -3.4026e-01,
          -1.6067e+00]]])

In [34]:
model.eval()

with torch.no_grad():
    preds = model(dataset[817][0].unsqueeze(1))

In [35]:
preds

tensor([0.1353, 0.2434, 0.3906, 0.0290, 0.2016])